### ISSUE TITLE
Remote LabRecorder: Variable 'offset' is being used without being initialized

### ISSUE THREAD

**Issue by agricolab** [labstreaminglayer/App-LabRecorder#6]
I was attempting to record EEG data from BrainVisionRecorder, calling ```LabRecorderCLI.exe type='EEG'```. 
The console printed 
```
Found BrainVision RDA@DESKTOP-79JUEJU matching 'type='EEG''
Starting the recording, press Enter to quit
Opened the stream BrainVision RDA.
Received header for stream BrainVision RDA.
Started data collection for stream BrainVision RDA.
Timeout in time correction query for stream 1
```
then it threw 
![grafik](https://user-images.githubusercontent.com/20556511/48623751-dca03880-e9aa-11e8-86bf-fc34f4ca3453.png)

This error was reproducible, although the same command run  flawless a few days before on another machine. The error occurs also if  i start the recording via the remote LabRecorderGUI.  Note that the old LabRecorder version 1.13 records without error message, but when i attempt to load the data, it throws an LinAlgError("Matrix is not positive definite"). So both errors seems to be related to the clock-offset issue, but are throwing different errors.

**Comment by tstenner** [comment]
I remember fixing the clock offsets bug as if it was yesterday, mostly because it was yesterday. I haven't had time to upload the new binaries, but in some very rare circumstances the clock synchronization could time out nevertheless so this should be fixed.

**Comment by cboulay** [comment]
This error can still happen if the `in->time_correction(2)` call fails.
In [this](https://github.com/labstreaminglayer/App-LabRecorder/blob/6ab0e080570a87267c88885a5db9fcb5be482779/recording.cpp#L300-L310) block of code, shouldn't the rest of the code that depends on `now` and `offset` be inside the `try` block?

**Comment by tstenner** [comment]
> In this block of code, shouldn't the rest of the code that depends on now and offset be inside the try block?

Yes and I don't know why it isn't.
